function testNestedThrow(int a) (int) {
    exception e  = {};
    throw e;
    int x = 5;
    int y = 10;
}
