function testThrowErrorSuggestions() {
    error err = {
        message: "Error Occurred!!"
    };

    try {
        
    } catch(error err2) {

    } finally {
        throw 
    }
}